application: pagevista
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: PIL
  version: "1.1.7"

handlers:
- url: /static
  static_dir: static/

- url: /satic/nicEdit
  static_dir: static/nicEdit/

- url: /static/images
  static_dir: static/images/

- url: /.*
  script: main.app


